# Generated by Django 3.2 on 2022-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGenerator', '0004_auto_20220525_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('bId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('fId', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=30)),
                ('backends', models.ManyToManyField(to='AppGenerator.Backend')),
            ],
        ),
    ]
