# Generated by Django 3.2 on 2022-05-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGenerator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesadmin',
            name='id',
        ),
        migrations.AddField(
            model_name='filesadmin',
            name='projectID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
